#!/bin/bash

#
# This script installs all neccessary PECL and PEAR dependencies so that 
# you can run all build targets. May be you must run this script as root
# or with sudo.
#
# If you only want to use the PHP lib you do not need to install
# the dependencies.
#

# http://www.xdebug.org/
# Required for code coverage.
pecl install xdebug

# http://pear.php.net/package/PHP_CodeSniffer/redirected
pear install PHP_CodeSniffer

# http://www.phpdoc.org/
pear install PhpDocumentor

# http://www.phing.info/trac/
pear channel-discover pear.phing.info
pear install phing/phing

# https://github.com/sebastianbergmann/phpunit/
pear channel-discover pear.phpunit.de
pear channel-discover components.ez.no
pear channel-discover pear.symfony-project.com
pear install phpunit/PHPUnit

# https://github.com/mikey179/vfsStream
pear channel-discover pear.php-tools.net
pear install pat/vfsStream-beta

# http://pdepend.org/download/index.html
pear channel-discover pear.pdepend.org
pear install pdepend/PHP_Depend-beta

#http://phpmd.org/
pear channel-discover pear.phpmd.org
pear install --alldeps phpmd/PHP_PMD